### ISSUE TITLE
How is pretrained patch embedding kernel downsamples for 32x32 images?

### ISSUE THREAD

**Issue by HashmatShadab** [mo666666/When-Adversarial-Training-Meets-Vision-Transformers#1]
In the paper it is mentioned that :
**"To accommodate the smaller image size of CIFAR-10, we downsample the patch embedding kernel from 16 × 16 to 4 × 4."** 

How is the pretrained embedding kernel's kernel size changed? Or is this layer reinitialized from scratch?

**Comment by mo666666** [comment]
Thank you for your attention to this work. Our operation to the patch embedding kernel mainly follows https://github.com/RulinShao/on-the-adversarial-robustness-of-visual-transformer/blob/master/training/timm_vit/vit.py. For other ViT variants, we will publish our code as soon as possible!

Hope my reply could address your concerns!

**Comment by HashmatShadab** [comment]
Thanks for your reply. So what I understand is that after downsampling the patch embedding kernel and using a patch size of 4 for 32x32 images, the total number of patches created after passing the image through the patch embedding layer is 64, right?

**Comment by mo666666** [comment]
Yes, you are right.
