### ISSUE TITLE
Hello,dear Mo

### ISSUE THREAD

**Issue by Zero-coder** [mo666666/When-Adversarial-Training-Meets-Vision-Transformers#2]
Would you mind tell me your personal contact ,I would like to consult some info about Phd in your group,If it's inconvenient for you,this is my personal email address:jiangmaowei@sia.cn and wechat id: ipromisedad.I'm looking forward to your response.Best wishes to you.

**Comment by Zero-coder** [comment]
I'd like to join in your group for the interest involved in your group if there's still any vacancy for phd.

**Comment by mo666666** [comment]
Hello, Jiang. Thank you for the contact. I have joined you through WeChat. Here is some information for my supervisor: [Prof. Yisen Wang](https://yisenwang.github.io/). You can also directly send emails to him at yisen.wang@pku.edu.cn following [the Instructions](https://yisenwang.github.io/recruit.html).

**Comment by Zero-coder** [comment]
Thanks sincerely,Mo.

**Comment by Zero-coder** [comment]
Sorry for interruption, I still haven't received your wechat request，this is my wechat_id : ipromisedad
