### ISSUE TITLE
Line 191 of train_imagenet.py should be `if args.PRM:`

### ISSUE THREAD

**Issue by youzunzhi** [mo666666/When-Adversarial-Training-Meets-Vision-Transformers#3]
instead of `if not args.PRM:`

**Comment by mo666666** [comment]
Hi, Youzun! Thank you for pointing out this bug! I made this mistake when I organize the open-source code.  I will fix it and if you find any other problems, feel free to contact me in this or other **issues**. 
Best wishes!
Yichuan
