### ISSUE TITLE
Will the weights of the models be released??

### ISSUE THREAD

**Issue by HashmatShadab** [mo666666/When-Adversarial-Training-Meets-Vision-Transformers#4]

**Comment by mo666666** [comment]
Dear HashmatShadab, 
Thank you for your interest in our work. We would like to release the pre-trained weight of this repository. But the experiments are performed on a cluster that forbids downloading checkpoints to the local computers. Sorry for the inconvenience. We highly recommend that you can train the model by yourself. If you meet any other problems, feel free to contact me at mo666666@stu.pku.edu.cn or open a new issue.
