### ISSUE TITLE
Reproducing results on ViT-S.

### ISSUE THREAD

**Issue by HashmatShadab** [mo666666/When-Adversarial-Training-Meets-Vision-Transformers#5]
There is a comment in the code regarding loading ViT-S for CIFAR-10 experiments.    

if pretrained:
        # NOTE my scale was wrong for original weights, leaving this here until I have better ones for this model
        model_kwargs.setdefault('qk_scale', 768 ** -0.5)
    model = _create_vision_transformer('vit_small_patch16_224', pretrained=pretrained,args=args, **model_kwargs)

Will the results be reproduced using the same scale or changes have to be made?

**Comment by mo666666** [comment]
No change is needed to be made. You can just ignore the comment and successfully reproduce the results in the original paper.
