### ISSUE TITLE
train_cifar.py issue

### ISSUE THREAD

**Issue by REXKEV214** [mo666666/When-Adversarial-Training-Meets-Vision-Transformers#7]
train_cifar.py文件的第364行是否应该修改成
loss, acc, y = train_step(X_, y_, epoch_now, mixup_fn)

**Comment by mo666666** [comment]
您好，感谢对我们工作的关注，是的，确实X_, y_更合适，但是我跑的时候--accum-steps都是默认设置为1， 所以对于结果貌似没有影响

**Comment by mo666666** [comment]
我会尽快修正掉这个bug，如果有其他问题，也欢迎您在issue中提出
